name: Latest blog post workflow

on:
  schedule:
    # Runs on the first day of every month at midnight
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "3"
          feed_list: "https://greyboyle.hashnode.dev/rss.xml"
